name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        modules: qtwebengine
        setup-python: false
        cache: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add Windows dependencies
      if: runner.os == 'Windows'
      run: windeployqt build/Release/kant-loader.exe -no-network -no-positioning -no-printsupport -no-qml -no-qmltooling -no-quick -no-quickwidgets -no-serialport -no-svg -no-webchannel

    - name: Upload the Windows build
      uses: actions/upload-artifact@v3
      if: runner.os == 'Windows'
      with:
        name: kant-loader-Windows
        path: build/Release

    - name: Upload the Linux build
      uses: actions/upload-artifact@v3
      if: runner.os == 'Linux'
      with:
        name: kant-loader-ubuntu
        path: build/kant-loader
